#
#
# Розклади Таро
# tarot
#

- name: Індивідуальний розклад
  image: /images/shop/tarot/1.jpg
  description: |
    Розклад на ваше питання, якого немає в списку.
    Якщо ви плануєте задавати більше одного питання - вигідніше взяти формат консультації.
  price_eur: 23
  price_uah: 1000
  category: Розклади Таро

- name: Кельтський хрест
  image: /images/shop/tarot/2.jpg
  description: |
    Розклад "Кельтський хрест" допомагає клієнту отримати глибокий і всебічний аналіз конкретної ситуації або питання. 
    Він дозволяє виявити всі значущі аспекти та впливи, які можуть впливати на розвиток подій, і дає рекомендації щодо подальших дій.
    Кому підходить цей розклад:
    - Людям, які хочуть отримати глибоке розуміння певної ситуації або питання.
    - Тим, хто шукає керівництво у складних або важливих життєвих ситуаціях.
    - Усім, хто прагне отримати чітку картину впливів та можливостей для прийняття обґрунтованих рішень.
  price_eur: 23
  price_uah: 1000
  category: Розклади Таро

- name: Таємниці
  image: /images/shop/tarot/3.jpg
  description: |
    Розклад "Таємниці" допомагає клієнту виявити та зрозуміти приховані фактори, які можуть впливати на його життя. 
    Це може включати розкриття прихованих мотивів, невідомих впливів, секретів або підсвідомих процесів.
    Кому підходить цей розклад:
    - Людям, які відчувають, що в їхньому житті є невідомі або приховані фактори, що впливають на їхні рішення та дії.
    - Тим, хто хоче глибше зрозуміти себе, свої мотиви та підсвідомі процеси.
    - Усім, хто шукає ясності у заплутаних або незрозумілих ситуаціях.
  price_eur: 23
  price_uah: 1000
  category: Розклади Таро

- name: Місяць
  image: /images/shop/tarot/4.jpg
  description: |
    Розклад "Місяць" допомагає клієнту отримати уявлення про те, що чекає його в найближчий місяць, і як найкраще використати цей час. 

    Це включає прогнозування ключових подій, потенційних викликів та можливостей, а також надання рекомендацій для успішного проходження кожного тижня.

    Кому підходить цей розклад:
    - Людям, які хочуть отримати чітке уявлення про майбутній місяць і планувати свої дії відповідно.
    - Тим, хто шукає керівництво та натхнення на щодень.
    - Усім, хто прагне більш глибокого розуміння своїх дій та їхніх наслідків у короткостроковій перспективі.
  price_eur: 23
  price_uah: 1000
  category: Розклади Таро

- name: Несподіванка
  image: /images/shop/tarot/5.jpg
  description: |
    Розклад "Несподіванка" допомагає виявити приховані події, обставини або можливості, про які клієнт може не підозрювати. 

    Він спрямований на те, щоб підготувати людину до раптових змін та показати, як найкраще зреагувати на них.

    Кому підходить цей розклад:
    - Людям, які відчувають невизначеність щодо майбутнього і хочуть бути готовими до будь-яких сюрпризів.
    - Тим, хто бажає отримати більше контролю над своїм життям, розуміючи потенційні несподіванки.
    - Усім, хто шукає нові можливості та не боїться змін.
  price_eur: 23
  price_uah: 1000
  category: Розклади Таро

- name: Сім днів
  image: /images/shop/tarot/6.jpg
  description: |
    Розклад "Сім днів" надає індивідуальні прогнози та рекомендації на кожен день тижня. 

    Він допомагає отримати ясність та впевненість у прийнятті рішень, зрозуміти можливі перешкоди та знайти шляхи для їх подолання.

    Кому підходить цей розклад: 
    - Людям, які хочуть отримати чітке уявлення про майбутній тиждень.
    - Тим, хто шукає керівництво та натхнення на кожен день.
    - Усім, хто прагне більш глибокого розуміння своїх дій та їхніх наслідків у короткостроковій перспективі.
  price_eur: 23
  price_uah: 1000
  category: Розклади Таро

#
#
# Передбачення на рунах
# runic
#

- name: Індивідуальний розклад
  image: /images/shop/runes/1.jpg
  description: |
    Розклад на ваше питання, якого немає в списку.
    Якщо ви плануєте задавати більше одного питання - вигідніше взяти формат консультації.
  price_eur: 23
  price_uah: 1000
  category: Передбачення на рунах

- name: Професія
  image: /images/shop/runes/2.jpg
  description: |
    "Розклад Професія" допомагає клієнту отримати чітке уявлення про свій професійний шлях, виявити сильні та слабкі сторони, оцінити поточні можливості та виклики, а також знайти оптимальні шляхи для досягнення професійних цілей.
    Кому підходить цей розклад:
    - Людям, які стоять перед вибором професійного шляху або хочуть змінити роботу.
    - Тим, хто шукає способи для кар'єрного зростання та професійного розвитку.
    - Усім, хто прагне отримати чіткі рекомендації щодо своїх професійних можливостей та викликів.
  price_eur: 23
  price_uah: 1000
  category: Передбачення на рунах

- name: Гості від Морфея
  image: /images/shop/runes/3.jpg
  description: |
    "Гості від Морфея" допомагає клієнту зрозуміти значення його снів, виявити приховані послання, які вони можуть містити, і дізнатися, як ці інсайти можуть вплинути на його життя наяву.
    Кому підходить цей розклад:
    - Людям, які часто бачать яскраві або загадкові сни і хочуть зрозуміти їхнє значення.
    - Тим, хто відчуває, що їхні сни містять важливі послання або інсайти.
    - Усім, хто прагне глибшого розуміння своїх підсвідомих процесів та емоційних станів.
  price_eur: 23
  price_uah: 1000
  category: Передбачення на рунах

- name: Діагностика магічних здібностей
  image: /images/shop/runes/4.jpg
  description: |
    Діагностика магічних здібностей допомагає клієнту виявити свої приховані магічні здібності та зрозуміти, як їх розвивати і використовувати. 
    Він також надає інсайти щодо поточних обмежень та потенціалу для розвитку магічних навичок.
    Кому підходить цей розклад:
    - Людям, які відчувають, що мають магічні здібності, але не впевнені, як їх розвивати і використовувати.
    - Тим, хто цікавиться магією та хоче зрозуміти свої вроджені таланти і можливості в цій сфері.
    - Усім, хто прагне глибшого розуміння своїх прихованих здібностей і бажає їх розвивати.
  price_eur: 23
  price_uah: 1000
  category: Передбачення на рунах

#
#
# Послуги
# services
#

- name: Текстова консультація
  image: /images/shop/services/1.png
  description: |
    Консультація в текстовому форматі протягом 30хв.
    На ній можна розбирати будь-які питання за допомогою рун та карт Таро.
  price_eur: 34
  price_uah: 1500
  category: Послуги

- name: Голосова консультація
  image: /images/shop/services/2.png
  description: |
    Консультація у аудіо-форматі протягом 30хв.
    На ній можна розбирати будь-які питання за допомогою рун та карт Таро а також допомога у вирішенні ваших проблем.
  price_eur: 45
  price_uah: 2000
  category: Послуги

- name: Питання Духам
  image: /images/shop/services/3.png
  description: |
    Відкрийте для себе мудрість древніх традицій за допомогою нашої унікальної послуги — Питання Духам. Ця послуга дозволяє вам отримати відповіді на важливі питання, поради та підтримку.
    Що входить в цю послугу:
    - Ви можете задати до п'яти коротких запитань або ж до трьох довгих.
    - Консультація по питанням та проблемам.
  price_eur: 64
  price_uah: 2850
  category: Послуги

- name: Дороги звірів
  image: /images/shop/services/4.png
  description: |
    Відкрийте нові можливості та усуньте перешкоди на шляху до ваших цілей з нашою послугою "Дороги звірів". 
    Цей ритуал допоможе вам залучити позитивні зміни, розчистити енергетичні блоки та налаштувати життя на гармонійний лад.
    Що входить у послугу:
    - Енергетичне очищення
    - Ритуали на відкриття доріг
    - Індивідуальні рекомендації
  price_eur: 101
  price_uah: 4500
  category: Послуги

#
#
# Чистка і захист
# cleaning_and_protection
#

- name: Спис і меч
  image: /images/shop/cleaning_and_protection/1.png
  description: |
    Спеціальний тип чистки і захисту у випадках, якщо на людині є прокляття або ж родові негативні маніпуляції.
    Для цього ритуалу обов’язково потрібна діагностика.
  price_eur: 112
  price_uah: 5000
  category: Чистка і захист

- name: Маля Фреї
  image: /images/shop/cleaning_and_protection/2.png
  description: |
    Індивідуальна чистка і захист дитини.
    Додатково можна запросити гармонізуючий амулет на основі речі, яку носить дитина (прикраса, браслет, тощо).
  price_eur: 68
  price_uah: 3000
  category: Чистка і захист

- name: Рунічне коло
  image: /images/shop/cleaning_and_protection/3.png
  description: |
    Повноцінна чистка і захист за допомогою рун.
    - чистка проводиться на основі діагностики
    - тип захисту на ваш особистий вибір, або повний або частковий
    Ця чистка підходить під будь-які запити.
  price_eur: 86
  price_uah: 3800
  category: Чистка і захист

- name: Шаманське дзеркало
  image: /images/shop/cleaning_and_protection/4.png
  description: |
    Повноцінна чистка і захист з використанням бубна, родових або духів місцевості та рун.
    - чистка проводиться на основі діагностики
    - тип захисту та від чого саме потрібно захистити, обираєте Ви
    Ця чистка підходить під будь-які запити.
  price_eur: 108
  price_uah: 4800
  category: Чистка і захист

#
#
# Грошові ритуали
# money_rituals
#

#
#
# Деструктивні ритуали
# destructive_rituals
#

#
#
# Любовні ритуали
# love_rituals
#

#
#
# Рунічні амулети
# runic_amulet
#

#
#
# Рунічні палиці
# staffir
#

#
#
# Рунічні свічки
# runic_candle
#

#
#
# Навчання
# education
#